# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d444f12790db4b2a2a472a24e3390735bee162af12d22a311e4218646fe22a5d2bb3c997255fb8db02374b42a1a9b9ca9280c23d125cb21d2f7f3e7e21b659

test:
  secret_key_base: c7188303497dd1b531f2c88df0cdbb48554f7d1dca4c1ea2c73d44654367d145ca114a6b1c550c44cb8f55868d9ae03943cb8d3111bc220bff58398b39dc0f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
